# Generated by Django 5.2.3 on 2025-06-27 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(default='1h', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='instructor',
            field=models.CharField(blank=True, default='Instructeur inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.CharField(default='Tous niveaux', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='Lieu non précisé', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.CharField(default='Gratuit', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport_zen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
