# Generated by Django 5.2.3 on 2025-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_category_activity_date_activity_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
