# Generated by Django 5.2.3 on 2025-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si False, réservée au créateur/business'),
        ),
    ]
