# Generated by Django 5.2.3 on 2025-07-04 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='participants',
        ),
        migrations.AddField(
            model_name='activity',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='registered_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
