# Generated by Django 5.2.3 on 2025-07-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_activity_participants_activity_attendees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time']},
        ),
    ]
