# Generated by Django 5.2.3 on 2025-07-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
    ]
