# Generated by Django 5.2.3 on 2025-07-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.CharField(blank=True, choices=[('inside', 'Intérieur'), ('outside', 'Extérieur')], help_text="Lieu : 'inside' ou 'outside' (nullable temporaire)", max_length=10, null=True),
        ),
    ]
