# Generated by Django 5.2.3 on 2025-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='venue',
            field=models.CharField(choices=[('inside', 'Intérieur'), ('outside', 'Extérieur')], default='inside', help_text="Lieu : 'inside' ou 'outside' (nullable temporaire)", max_length=10),
        ),
    ]
