# Generated by Django 5.2.3 on 2025-07-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='company',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
