# Generated by Django 5.2.3 on 2025-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_plan_remove_invitation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('rating', models.FloatField(default=0.0)),
                ('sport_zen', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
