# Generated by Django 5.2.3 on 2025-07-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscriptionrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionrequest',
            options={'verbose_name': 'Demande d’abonnement', 'verbose_name_plural': 'Demandes d’abonnement'},
        ),
    ]
